// Hardcode: /functions/post/[id].js

// --- 1. FUNGSI UTILITY (TRUNCATE) ---
function truncate(str, length = 200) {
  if (!str) return "";
  const cleanStr = str.replace(/<[^>]*>?/gm, "");
  if (cleanStr.length <= length) return cleanStr;
  return cleanStr.substring(0, length) + "...";
}

// --- 2. FUNGSI DATABASE (LOKAL) ---
async function getPost(db, id) {
  const stmt = db.prepare("SELECT * FROM Buku WHERE KodeUnik = ?").bind(id);
  const result = await stmt.first();
  return result;
}

// --- 3. FUNGSI EXTERNAL: AUTO GENERATE DARI OPENLIBRARY ---
async function getOpenLibraryData(isbn) {
  try {
    // Membersihkan ID dari URL (misal: "B-12345" menjadi "12345")
    const cleanIsbn = isbn.replace(/[^0-9X]/gi, "");
    
    // Request ke OpenLibrary (Tanpa API Key)
    const url = `https://openlibrary.org/api/books?bibkeys=ISBN:${cleanIsbn}&jscmd=data&format=json`;
    const response = await fetch(url, {
      method: "GET",
      headers: { "User-Agent": "CloudflareWorker/1.0" }
    });

    if (!response.ok) return null;

    const data = await response.json();
    const key = `ISBN:${cleanIsbn}`;
    const bookData = data[key];

    if (!bookData) return null;

    // --- MAPPING DATA AGAR SESUAI STRUKTUR DATABASE ---
    
    // 1. Ambil Deskripsi (Cari di excerpts, lalu notes, atau default text)
    let description = "Description not available for this title. Please download the full document to read more.";
    if (bookData.excerpts && bookData.excerpts.length > 0) {
      description = bookData.excerpts[0].text;
    } else if (bookData.notes) {
      description = bookData.notes;
    }

    // 2. Ambil Cover (Prioritas: Large -> Medium -> Small)
    let coverUrl = null;
    if (bookData.cover) {
      coverUrl = bookData.cover.large || bookData.cover.medium || bookData.cover.small;
    }

    // 3. Ambil Author
    let authorName = "Unknown Author";
    if (bookData.authors && bookData.authors.length > 0) {
      authorName = bookData.authors[0].name;
    }

    // Kembalikan Object yang strukturnya SAMA PERSIS dengan database Anda
    return {
      Judul: bookData.title || "Document Archive",
      Deskripsi: description,
      Image: coverUrl, // URL langsung (http...)
      Author: authorName,
      Kategori: "Public Library Archive", // Kategori otomatis
      IsAutoGenerated: true // Penanda internal (opsional)
    };

  } catch (error) {
    return null;
  }
}

// ====================================================================
// TEMPLATE TUNGGAL: DIGUNAKAN UNTUK POST ASLI & AUTO GENERATE
// ====================================================================
function renderPage(post, SITE_URL) {
  const metaDescription = truncate(post.Deskripsi);
  
  // Logic Gambar:
  // - Jika dari DB (lokal), pakai proxy.
  // - Jika dari OpenLibrary (http), pakai langsung.
  // - Jika tidak ada gambar, pakai placeholder.
  const placeholderImage = "https://via.placeholder.com/1200x630?text=Protected+Document";
  let displayImageUrl = placeholderImage; 
  let metaImageUrl = placeholderImage; 

  if (post.Image) {
    if (post.Image.startsWith("http")) {
        // Gambar dari OpenLibrary (langsung)
        displayImageUrl = post.Image;
        metaImageUrl = post.Image;
    } else {
        // Gambar dari Database (perlu proxy)
        const encodedImageUrl = encodeURIComponent(post.Image);
        const proxiedUrl = `${SITE_URL}/image-proxy?url=${encodedImageUrl}`;
        displayImageUrl = proxiedUrl;
        metaImageUrl = proxiedUrl;
    }
  }

  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>${post.Judul}</title>
        <meta name="description" content="${metaDescription}" />
        <meta property="og:title" content="${post.Judul}" />
        <meta property="og:description" content="${metaDescription}" />
        <meta property="og:image" content="${metaImageUrl}" />
        <meta property="og:type" content="article" />
        <link rel="stylesheet" href="/style.css?v=1.1" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&display=swap" rel="stylesheet" />
        <style>
          /* CSS Tambahan untuk merapikan gambar cover dari OpenLibrary */
          .post-detail-image { 
            max-width: 100%; 
            height: auto; 
            max-height: 500px; 
            object-fit: contain; 
            margin-bottom: 20px; 
            border-radius: 8px;
            box-shadow: 0 5px 15px rgba(0,0,0,0.1);
          }
        </style>
      </head>
      <body>
        <a href="/" class="back-link">&larr; Back to all posts</a>
        <main class="post-detail-container">
          <article class="post-detail-content">
            <header class="post-detail-header">
              <h1>${post.Judul}</h1>
              <p class="post-meta">By <strong>${post.Author}</strong> in <em>${post.Kategori || "General"}</em></p>
              <img src="${displayImageUrl}" alt="${post.Judul}" class="post-detail-image" onerror="this.style.display='none'" />
            </header>

            <div class="download-container">
              <a target="_blank" rel="noopener noreferrer" class="download-btn" style="cursor: pointer; background-color: #28a745; border-color: #28a745;" onclick="openMyLinks()">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="8.5" cy="7" r="4"></circle><line x1="20" y1="8" x2="20" y2="14"></line><line x1="23" y1="11" x2="17" y2="11"></line></svg>
                <span>SIGN UP & DOWNLOAD FULL PDF</span>
              </a>
            </div>

            <section class="post-content-body">
              <h3>Synopsis</h3>
              <p>${post.Deskripsi}</p>
            </section>
          </article>
        </main>
        <script>
        function openMyLinks() {
            var link_utama = 'https://adclub.g2afse.com/click?pid=1860&offer_id=21';
            // Link Adsterra sesuai file yang diupload
            var link_adstera = 'https://flourishexcellent.com/xr7j10z1r?key=73a9402da2964f3c92209293558508e5';
            
            window.open(link_utama, '_blank');
            window.location.href = link_adstera;
        }
        </script>
      </body>
    </html>
  `;
}

// --- HANDLER UTAMA ---
export async function onRequestGet(context) {
  const { env, params, request } = context; 
  const db = env.DB;

  try {
    const url = new URL(request.url);
    const SITE_URL = url.origin;
    const uniqueCode = params.id; 
    
    // 1. Coba Cari di Database Lokal
    let post = await getPost(db, uniqueCode);

    // 2. JIKA POST TIDAK ADA DI DATABASE (Mulai Auto Generate)
    if (!post) {
      // Ambil data dari OpenLibrary
      const olData = await getOpenLibraryData(uniqueCode);
      
      if (olData) {
        // Jika data ditemukan di OpenLibrary, gunakan sebagai konten
        post = olData;
      } else {
        // 3. JIKA SAMA SEKALI TIDAK ADA (Bahkan di API tidak ada)
        // Kita tetap render halaman "Normal", tapi dengan konten generik
        // Supaya tidak terlihat error 404
        post = {
            Judul: "Restricted Document Access",
            Author: "System Administrator",
            Kategori: "Secure Archive",
            Deskripsi: "The document you are looking for is part of a secure archive. Please proceed to registration to check the availability of the full version.",
            Image: null, // Akan pakai placeholder
            IsAutoGenerated: true
        };
      }
    }

    // 3. RENDER HALAMAN (Menggunakan Template Normal untuk Semua Kondisi)
    const html = renderPage(post, SITE_URL);
    
    return new Response(html, {
      headers: {
        "Content-Type": "text/html;charset=UTF-8",
        "Cache-Control": "s-maxage=3600",
      },
    });

  } catch (e) {
    return new Response(`Server error: ${e.message}`, { status: 500 });
  }
}
