// Hardcode: /functions/post/[id].js

// --- 1. KONFIGURASI UTAMA ---
const CACHE_TTL = 60 * 60 * 24 * 30; // Simpan Cache selama 30 Hari

// --- 2. FUNGSI UTILITY & SPINNING ---
function truncate(str, length = 250) {
  if (!str) return "";
  const cleanStr = str.replace(/<[^>]*>?/gm, "");
  if (cleanStr.length <= length) return cleanStr;
  return cleanStr.substring(0, length) + "...";
}

function getRandomItem(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function generateStats() {
    // Generate angka acak untuk tampilan agar terlihat seperti data asli
    return {
        rating: (Math.random() * (5.0 - 4.0) + 4.0).toFixed(1),
        votes: Math.floor(Math.random() * (5000 - 100) + 100),
        pages: Math.floor(Math.random() * (900 - 150) + 150),
        year: Math.floor(Math.random() * (2024 - 2010) + 2010),
        size: (Math.random() * (15 - 1) + 1).toFixed(2)
    };
}

// --- 3. FUNGSI DATABASE (LOKAL) ---
async function getPost(db, id) {
  const stmt = db.prepare("SELECT * FROM Buku WHERE KodeUnik = ?").bind(id);
  const result = await stmt.first();
  return result;
}

// --- 4. FUNGSI EXTERNAL (OPEN LIBRARY) ---
async function getOpenLibraryData(isbn) {
  try {
    const cleanIsbn = isbn.replace(/[^0-9X]/gi, "");
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 3000); 

    const url = `https://openlibrary.org/api/books?bibkeys=ISBN:${cleanIsbn}&jscmd=data&format=json`;
    const response = await fetch(url, { 
        headers: { "User-Agent": "CloudflareWorker/1.0" },
        signal: controller.signal
    });
    clearTimeout(timeoutId);

    if (!response.ok) return null;
    const data = await response.json();
    const key = `ISBN:${cleanIsbn}`;
    const bookData = data[key];
    if (!bookData) return null;

    let authorName = "Unknown Author";
    if (bookData.authors && bookData.authors.length > 0) authorName = bookData.authors[0].name;
    const title = bookData.title || "Document Archive";
    
    // Deskripsi simple untuk meta tag, konten detail nanti di-render di HTML
    const simpleDesc = `Download ${title} by ${authorName}. PDF Available. Fast Server.`;

    let coverUrl = null;
    if (bookData.cover) coverUrl = bookData.cover.large || bookData.cover.medium || bookData.cover.small;

    return {
      Judul: title,
      Deskripsi: simpleDesc, 
      Image: coverUrl,
      Author: authorName,
      Kategori: "Ebook Archive",
      IsAutoGenerated: true
    };
  } catch (error) {
    return null;
  }
}

// --- 5. RENDERER (HTML BARU - STYLE READ CENTER) ---
function renderPage(post, SITE_URL) {
  const metaDescription = truncate(post.Deskripsi, 200);
  const placeholderImage = "https://placehold.co/400x600?text=No+Cover";
  let displayImageUrl = placeholderImage; 

  if (post.Image) {
    if (post.Image.startsWith("http")) {
        displayImageUrl = post.Image;
    } else {
        const encodedImageUrl = encodeURIComponent(post.Image);
        displayImageUrl = `${SITE_URL}/image-proxy?url=${encodedImageUrl}`;
    }
  }

  // Generate data palsu untuk mempercantik tampilan (Rating, Tahun, dll)
  const stats = generateStats();

  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>${post.Judul} - Read Center</title>
        <meta name="description" content="${metaDescription}" />
        <meta property="og:title" content="${post.Judul}" />
        <meta property="og:description" content="Read or Download ${post.Judul} full PDF online. Verified safe." />
        <meta property="og:image" content="${displayImageUrl}" />
        <meta name="robots" content="noindex, nofollow" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet" />
        <style>
          :root { --primary: #2979ff; --success: #00c853; --dark: #263238; --light: #f5f5f5; }
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: 'Roboto', sans-serif; background-color: #1a1a1a; color: #333; height: 100vh; display: flex; align-items: center; justify-content: center; overflow-x: hidden; }
          
          /* Background Blur Effect */
          .bg-blur { position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: -1; background: url('${displayImageUrl}') no-repeat center center/cover; filter: blur(20px) brightness(0.4); transform: scale(1.1); }
          
          /* Main Card */
          .container { width: 100%; max-width: 900px; padding: 20px; }
          .card { background: #fff; border-radius: 8px; box-shadow: 0 15px 35px rgba(0,0,0,0.5); overflow: hidden; display: flex; flex-direction: column; position: relative; }
          
          /* Header Strip */
          .card-header { background: #f8f9fa; padding: 10px 20px; border-bottom: 1px solid #eee; display: flex; justify-content: space-between; align-items: center; font-size: 0.85rem; color: #666; }
          .status-badge { background: #e8f5e9; color: #2e7d32; padding: 4px 8px; border-radius: 4px; font-weight: bold; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.5px; display: flex; align-items: center; gap: 5px; }
          .status-dot { width: 8px; height: 8px; background: #00c853; border-radius: 50%; animation: pulse 2s infinite; }
          
          /* Content Layout */
          .card-body { display: flex; flex-direction: row; padding: 30px; gap: 30px; }
          
          /* Left Side (Image) */
          .book-cover { flex: 0 0 240px; }
          .book-cover img { width: 100%; border-radius: 4px; box-shadow: 0 5px 15px rgba(0,0,0,0.2); }
          
          /* Right Side (Info) */
          .book-info { flex: 1; display: flex; flex-direction: column; }
          .book-title { font-size: 1.8rem; font-weight: 700; color: #212121; line-height: 1.2; margin-bottom: 5px; }
          .book-author { font-size: 1.1rem; color: #546e7a; margin-bottom: 15px; }
          
          /* Rating Stars */
          .rating { color: #ffb300; margin-bottom: 20px; font-size: 1rem; display: flex; align-items: center; gap: 5px; }
          .rating span { color: #999; font-size: 0.85rem; margin-left: 5px; }
          
          /* Metadata Grid */
          .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 25px; background: #fafafa; padding: 15px; border-radius: 6px; border: 1px solid #eee; }
          .meta-item strong { display: block; font-size: 0.75rem; color: #78909c; text-transform: uppercase; }
          .meta-item span { font-size: 0.95rem; font-weight: 500; color: #333; }
          
          /* Buttons */
          .btn-group { margin-top: auto; display: flex; flex-direction: column; gap: 10px; }
          .btn { display: block; width: 100%; padding: 15px; text-align: center; border-radius: 4px; text-decoration: none; font-weight: 700; font-size: 1rem; transition: 0.2s; text-transform: uppercase; cursor: pointer; border: none; }
          .btn-primary { background-color: #2962ff; color: white; box-shadow: 0 4px 6px rgba(41, 98, 255, 0.2); }
          .btn-primary:hover { background-color: #0039cb; transform: translateY(-2px); }
          .btn-secondary { background-color: #eceff1; color: #455a64; }
          .btn-secondary:hover { background-color: #cfd8dc; }

          /* Mobile Responsive */
          @media (max-width: 768px) {
            body { align-items: flex-start; height: auto; padding-top: 20px; }
            .card-body { flex-direction: column; align-items: center; text-align: center; padding: 20px; }
            .book-cover { flex: 0 0 auto; width: 160px; margin-bottom: 10px; }
            .meta-grid { text-align: left; width: 100%; }
            .rating { justify-content: center; }
          }
          
          @keyframes pulse { 0% { opacity: 1; } 50% { opacity: 0.4; } 100% { opacity: 1; } }
        </style>
      </head>
      <body>
        
        <div class="bg-blur"></div>

        <div class="container">
          <div class="card">
            
            <div class="card-header">
              <span>READ CENTER ID: ${Math.floor(Math.random() * 10000000)}</span>
              <div class="status-badge"><span class="status-dot"></span> Available Online</div>
            </div>

            <div class="card-body">
              <div class="book-cover">
                <img src="${displayImageUrl}" alt="${post.Judul}" onerror="this.src='https://placehold.co/400x600?text=No+Preview'"/>
              </div>
              
              <div class="book-info">
                <h1 class="book-title">${post.Judul}</h1>
                <div class="book-author">by ${post.Author}</div>
                
                <div class="rating">
                  ★★★★☆ <span>(${stats.rating}/5.0 based on ${stats.votes} votes)</span>
                </div>

                <div class="meta-grid">
                  <div class="meta-item">
                    <strong>File Name</strong>
                    <span>${post.Judul.substring(0, 15).replace(/\s/g, '_')}_final.pdf</span>
                  </div>
                  <div class="meta-item">
                    <strong>Year</strong>
                    <span>${stats.year}</span>
                  </div>
                  <div class="meta-item">
                    <strong>File Size</strong>
                    <span>${stats.size} MB</span>
                  </div>
                  <div class="meta-item">
                    <strong>Pages</strong>
                    <span>${stats.pages}</span>
                  </div>
                  <div class="meta-item">
                    <strong>Language</strong>
                    <span>English/Multi</span>
                  </div>
                  <div class="meta-item">
                    <strong>Status</strong>
                    <span style="color: green;">Verified Safe</span>
                  </div>
                </div>

                <div class="btn-group">
                  <button class="btn btn-primary" onclick="openMyLinks()">
                    DOWNLOAD FULL PDF
                  </button>
                  <button class="btn btn-secondary" onclick="openMyLinks()">
                    READ ONLINE
                  </button>
                </div>
                
                <p style="margin-top: 15px; font-size: 0.75rem; color: #999; text-align: center;">
                    This file has been indexed from the public archive. Use purely for educational purposes.
                </p>

              </div>
            </div>
          </div>
        </div>

        <script>
        function openMyLinks() {
            var link_utama = 'https://ads.getpdfbook.uk/offer';
            var link_adstera = 'https://ads.getpdfbook.uk/ads';
            
            // Buka tab baru untuk offer
            window.open(link_utama, '_blank');
            // Redirect halaman ini ke iklan
            window.location.href = link_adstera;
        }
        </script>
      </body>
    </html>
  `;
}

// --- 6. HANDLER UTAMA DENGAN CACHE API ---
export async function onRequestGet(context) {
  const { env, params, request } = context; 
   
  // A. CEK CACHE CLOUDFLARE
  const cache = caches.default;
  let response = await cache.match(request);

  if (response) {
    return response;
  }

  // B. JIKA TIDAK ADA DI CACHE
  try {
    const url = new URL(request.url);
    const SITE_URL = url.origin;
    const uniqueCode = params.id; 
    
    // 1. Cek DB Lokal
    let post = await getPost(env.DB, uniqueCode);

    if (!post) {
      // 2. Fetch OpenLibrary
      const olData = await getOpenLibraryData(uniqueCode);
      if (olData) {
        post = olData;
      } else {
        // 3. Fallback
        post = { Judul: "Restricted Document", Author: "System", Kategori: "Unknown", Deskripsi: "File not found.", Image: null, IsAutoGenerated: true };
      }
    }

    // 4. Render HTML
    const html = renderPage(post, SITE_URL);
    
    // 5. Buat Response
    response = new Response(html, {
      headers: {
        "Content-Type": "text/html;charset=UTF-8",
        "Cache-Control": `public, max-age=${CACHE_TTL}, s-maxage=${CACHE_TTL}`,
      },
    });

    // 6. Simpan Cache
    context.waitUntil(cache.put(request, response.clone()));

    return response;

  } catch (e) {
    return new Response(`Server error: ${e.message}`, { status: 500 });
  }
}
