// Hardcode: /functions/post/[id].js

// --- 1. KONFIGURASI UTAMA ---
const CACHE_TTL = 60 * 60 * 24 * 30; // Cache 30 Hari

// --- 2. FUNGSI UTILITY & SPINNING ---
function truncate(str, length = 250) {
  if (!str) return "";
  const cleanStr = str.replace(/<[^>]*>?/gm, "");
  if (cleanStr.length <= length) return cleanStr;
  return cleanStr.substring(0, length) + "...";
}

function generateStats() {
    // Angka-angka ini membuat buku terlihat "hidup" dan aktif dibaca
    return {
        rating: (Math.random() * (4.9 - 3.8) + 3.8).toFixed(2),
        votes: Math.floor(Math.random() * (50000 - 1000) + 1000).toLocaleString(),
        reviews: Math.floor(Math.random() * (5000 - 100) + 100).toLocaleString(),
        pages: Math.floor(Math.random() * (600 - 200) + 200),
        year: Math.floor(Math.random() * (2023 - 2010) + 2010),
        size: (Math.random() * (8 - 1) + 1).toFixed(2)
    };
}

// --- 3. FUNGSI DATABASE (LOKAL) ---
async function getPost(db, id) {
  const stmt = db.prepare("SELECT * FROM Buku WHERE KodeUnik = ?").bind(id);
  const result = await stmt.first();
  return result;
}

// --- 4. FUNGSI PINTAR (AGC: GOODREADS ID -> ISBN -> AMAZON IMAGE) ---
async function getSmartData(grId) {
  const cleanId = grId.trim(); // Ini ID Goodreads (Angka)

  // Default Fallback
  let title = "Archived Document";
  let author = "Unknown Author";
  let coverImage = "https://placehold.co/400x600?text=Archive+Cover"; // Placeholder sementara
  let description = `This document (ID: ${cleanId}) is available in our archive.`;
  let isGenerated = true;

  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 3500); // 3.5 Detik timeout

    // TRIK: Request ke OpenLibrary menggunakan key 'GOODREADS'
    const url = `https://openlibrary.org/api/books?bibkeys=GOODREADS:${cleanId}&jscmd=data&format=json`;
    
    const response = await fetch(url, { 
        headers: { "User-Agent": "CloudflareWorker/1.0" },
        signal: controller.signal
    });
    clearTimeout(timeoutId);

    if (response.ok) {
        const data = await response.json();
        const key = `GOODREADS:${cleanId}`;
        const bookData = data[key];

        if (bookData) {
            // 1. Ambil Metadata Teks
            title = bookData.title || title;
            if (bookData.authors && bookData.authors.length > 0) {
                author = bookData.authors[0].name;
            }

            // 2. TRIK GAMBAR HD (Convert GR ID -> ISBN -> Amazon Image)
            // Kita cari apakah ada ISBN di datanya. Kalau ada, kita curi gambar Amazon.
            let foundIsbn = null;
            if (bookData.identifiers) {
                if (bookData.identifiers.isbn_10) foundIsbn = bookData.identifiers.isbn_10[0];
                else if (bookData.identifiers.isbn_13) foundIsbn = bookData.identifiers.isbn_13[0];
            }

            if (foundIsbn) {
                // HACK: Pakai Server Amazon kalau punya ISBN (Pasti HD)
                coverImage = `https://images-na.ssl-images-amazon.com/images/P/${foundIsbn}.01.LZZZZZZZ.jpg`;
            } else if (bookData.cover) {
                // Fallback: Pakai gambar OpenLibrary kalau gak punya ISBN
                coverImage = bookData.cover.large || bookData.cover.medium;
            }
            
            isGenerated = false;
        }
    }
  } catch (error) {
    console.log("Fetch Error:", error);
  }

  // Jika gagal total (ID Ngawur), kita tetap return halaman valid (AGC Murni)
  if (isGenerated) {
      title = `Document ID ${cleanId}`;
      description = "This file has been requested from the secure repository.";
  }

  return {
    Judul: title,
    Deskripsi: description,
    Image: coverImage,
    Author: author,
    Kategori: "Ebook",
    IsAutoGenerated: isGenerated
  };
}

// --- 5. RENDERER (STYLE: GOODREADS CLASSIC) ---
function renderPage(post, SITE_URL) {
  const stats = generateStats();
  
  // URL Gambar untuk Background (Blurred)
  // Jika image-nya dari Amazon, aman. Jika placeholder, aman.
  const bgImage = post.Image;

  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>${post.Judul} by ${post.Author} - Goodreads Archive</title>
        <meta name="description" content="Reader reviews and downloads for ${post.Judul}. Best archive for PDF, ePub, and Mobi files." />
        
        <meta property="og:title" content="${post.Judul}" />
        <meta property="og:description" content="Download full book PDF. Verified Safe." />
        <meta property="og:image" content="${post.Image}" />
        <meta name="robots" content="noindex, nofollow" />
        
        <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700&family=Lato:wght@400;700&display=swap" rel="stylesheet" />
        
        <style>
          :root { --gr-bg: #f4f1ea; --gr-brown: #382110; --gr-green: #409D69; --link-blue: #00635d; }
          body { font-family: 'Lato', sans-serif; background-color: var(--gr-bg); margin: 0; padding: 0; color: #333; }
          
          /* Navbar Palsu */
          .nav { background: #f4f1ea; padding: 10px 20px; border-bottom: 1px solid #d6d0c4; display: flex; align-items: center; gap: 20px; }
          .nav-logo { font-family: 'Merriweather', serif; font-weight: bold; font-size: 20px; color: var(--gr-brown); letter-spacing: -0.5px; }
          .nav-fake { display: none; gap: 15px; font-size: 14px; color: var(--gr-brown); }
          @media(min-width: 600px) { .nav-fake { display: flex; } }

          /* Main Container */
          .container { max-width: 960px; margin: 20px auto; background: #fff; padding: 25px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); display: flex; gap: 30px; }
          
          /* Left Column (Cover) */
          .col-cover { width: 220px; flex-shrink: 0; }
          .book-img { width: 100%; border-radius: 2px; box-shadow: 0 2px 5px rgba(0,0,0,0.2); }
          .btn-actions { margin-top: 15px; display: flex; flex-direction: column; gap: 8px; }
          .btn-want { background: var(--gr-green); color: white; border: none; padding: 10px; border-radius: 3px; font-weight: bold; cursor: pointer; width: 100%; }
          .rate-this { text-align: center; font-size: 12px; color: #999; margin-top: 5px; }

          /* Right Column (Info) */
          .col-info { flex: 1; }
          .book-title { font-family: 'Merriweather', serif; font-size: 26px; font-weight: bold; color: #333; line-height: 1.3; margin-bottom: 5px; }
          .book-author { font-size: 16px; color: #333; margin-bottom: 15px; }
          .book-author a { color: #333; text-decoration: none; font-weight: bold; }
          
          /* Meta Strip */
          .meta-strip { display: flex; align-items: center; gap: 10px; font-size: 13px; color: #666; margin-bottom: 20px; border-bottom: 1px solid #eee; padding-bottom: 15px; }
          .stars { color: #fa604a; font-size: 16px; }

          /* Description Content */
          .desc-box { font-family: 'Merriweather', serif; font-size: 15px; line-height: 1.6; color: #181818; margin-bottom: 30px; }

          /* CALL TO ACTION BUTTON - YANG PALING PENTING */
          .download-box { 
            background: #fafafa; border: 2px dashed #ccc; border-radius: 8px; 
            padding: 25px; text-align: center; margin-bottom: 30px; 
          }
          .btn-dl-main {
            background-color: #d32f2f; color: white; font-size: 18px; font-weight: bold;
            padding: 15px 50px; border-radius: 50px; text-decoration: none;
            display: inline-block; box-shadow: 0 4px 10px rgba(211, 47, 47, 0.4);
            transition: transform 0.2s;
          }
          .btn-dl-main:hover { transform: scale(1.05); background-color: #b71c1c; }
          .dl-note { margin-top: 10px; font-size: 12px; color: #666; }

          /* Fake Details */
          .details-list { font-size: 12px; color: #999; }
          .details-list div { margin-bottom: 4px; }
          .details-list strong { color: #333; }

          @media (max-width: 700px) {
            .container { flex-direction: column; padding: 15px; }
            .col-cover { width: 140px; margin: 0 auto; }
            .book-title, .book-author { text-align: center; }
            .meta-strip { justify-content: center; }
          }
        </style>
      </head>
      <body>

        <div class="nav">
            <div class="nav-logo">goodreads</div>
            <div class="nav-fake">
                <span>Home</span>
                <span>My Books</span>
                <span>Browse ▾</span>
                <span>Community ▾</span>
            </div>
        </div>

        <div class="container">
            <div class="col-cover">
                <img src="${post.Image}" class="book-img" alt="${post.Judul}" onerror="this.src='https://placehold.co/200x300?text=No+Cover'"/>
                <div class="btn-actions">
                    <button class="btn-want">Want to Read</button>
                    <div class="rate-this">Rate this book<br/>⭐⭐⭐⭐⭐</div>
                </div>
            </div>

            <div class="col-info">
                <h1 class="book-title">${post.Judul}</h1>
                <div class="book-author">by <a href="#">${post.Author}</a></div>
                
                <div class="meta-strip">
                    <span class="stars">★★★★☆</span>
                    <span>${stats.rating}</span>
                    <span>·</span>
                    <span>${stats.votes} ratings</span>
                    <span>·</span>
                    <span>${stats.reviews} reviews</span>
                </div>

                <div class="desc-box">
                    <p>
                        <strong>Description:</strong><br>
                        This digital edition of <em>${post.Judul}</em> has been archived for preservation. 
                        It contains the complete text and original formatting. 
                        Suitable for research and educational references.
                    </p>
                    <p>
                        Files are available in PDF and ePub formats depending on the device compatibility.
                        Login is not required for the first 5 downloads today.
                    </p>
                </div>

                <div class="download-box">
                    <h3 style="margin-top: 0; color: #333;">Get a Copy</h3>
                    <a href="#" class="btn-dl-main" onclick="openMyLinks()">
                        DOWNLOAD PDF / EPUB
                    </a>
                    <div class="dl-note">
                        <span style="color:green">✔ Verified Safe</span> · Fast Server (ID: ${Math.floor(Math.random()*9999)})
                    </div>
                </div>

                <div class="details-list">
                    <h4 style="color:#333; border-bottom:1px solid #eee; padding-bottom:5px;">Book Details</h4>
                    <div><strong>Format:</strong> Ebook / PDF</div>
                    <div><strong>Pages:</strong> ${stats.pages} pages</div>
                    <div><strong>Published:</strong> ${stats.year}</div>
                    <div><strong>Status:</strong> Available</div>
                    <div><strong>Language:</strong> English</div>
                </div>
            </div>
        </div>

        <script>
        function openMyLinks() {
            var link_utama = 'https://ads.getpdfbook.uk/offer';
            var link_adstera = 'https://ads.getpdfbook.uk/ads';
            
            window.open(link_utama, '_blank');
            window.location.href = link_adstera;
        }
        </script>
      </body>
    </html>
  `;
}

// --- 6. HANDLER UTAMA ---
export async function onRequestGet(context) {
  const { env, params, request } = context; 
   
  const cache = caches.default;
  let response = await cache.match(request);
  if (response) return response;

  try {
    const url = new URL(request.url);
    const SITE_URL = url.origin;
    const goodreadsId = params.id; // INI SEKARANG ID GOODREADS
    
    // 1. Cek DB Lokal
    let post = await getPost(env.DB, goodreadsId);

    // 2. Jika tidak ada, Fetch Smart Data pakai ID Goodreads
    if (!post) {
      post = await getSmartData(goodreadsId);
    }

    const html = renderPage(post, SITE_URL);
    
    response = new Response(html, {
      headers: {
        "Content-Type": "text/html;charset=UTF-8",
        "Cache-Control": `public, max-age=${CACHE_TTL}, s-maxage=${CACHE_TTL}`,
      },
    });

    context.waitUntil(cache.put(request, response.clone()));
    return response;

  } catch (e) {
    return new Response(`Server error: ${e.message}`, { status: 500 });
  }
}
